const _d3 = require('d3');
const jsdom = require('jsdom');
const phantom = require('phantom');
const fs = require('fs');
const path = require('path');
const randomstring = require('randomstring');
const os = require('os');

class PrettyData {
    /**
     * Creates a new instance of PrettyData.
     * 
     * @param {number} width the width of the SVG element
     * @param {number} height the height of the SVG element
     */
    constructor(width = 960, height = 600) {
        const document = jsdom.jsdom();
        const root = _d3.select(document.body);
        this._svg = root.append('svg').attr('xmlns', 'http://www.w3.org/2000/svg').attr('width', width).attr('height', height);
        this._document = document;
        this._root = root;
    }

    static _writeSvgToFile(svg) {
        const filename = path.join(os.tmpdir(), `${randomstring.generate()}.svg`);
        return new Promise((resolve, reject) => {
            fs.writeFile(filename, svg, {encoding: 'utf8'}, error => {
                if(error) {
                    return reject(error);
                }
                resolve(filename);
            })
        });
    }

    static _renderPng(svgFile) {
        const pngFile = svgFile.replace('.svg', '.png');
        return new Promise((resolve, reject) => {
            let _ph, _page, _content;
            phantom.create()
                .then(ph => (_ph = ph) && ph.createPage())
                .then(page => (_page = page) && page.open(`file://${svgFile}`))
                .then(() => _page.render(pngFile, {format: 'png'}))
                .then(() => (_page.close() && _ph.exit()))
                .then(() => resolve(pngFile))
                .catch(reject);
        });
    }

    /**
     * Exposes the d3 library.
     */
    static get d3() {
        return _d3;
    }

    /**
     * Exposes the SVG element where d3 will render the data.
     */
    get svg() {
        return this._svg;
    }

    /**
     * Exports the HTML document that contains the SVG
     * generated by d3. If styles is set then the CSS
     * is inject into the document as a style element in the head.
     * 
     * @param {string} styles the stylesheet
     */
    html(styles) {
        if(styles) {
            const styleElement = this._document.createElement('style');
            styleElement.innerHTML = styles;
            this._document.querySelector('head').appendChild(styleElement);
        }
        return Promise.resolve(jsdom.serializeDocument(this._document));
    }
    
    png() {
        return this.export()
            .then(PrettyData._writeSvgToFile)
            .then(PrettyData._renderPng);
    }

    /**
     * Exports the SVG generated by d3.
     */
    export() {
        return Promise.resolve(this._root.select('svg').node().outerHTML);
    }
}

module.exports = PrettyData;